# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bunary.proto\x12\x05unary\"\"\n\x04\x41rgs\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x02\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x02\")\n\x06Result\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x02\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\xdb\x01\n\x05Unary\x12=\n\x11GetServerResponse\x12\x0e.unary.Message\x1a\x16.unary.MessageResponse\"\x00\x12#\n\x03\x41\x64\x64\x12\x0b.unary.Args\x1a\r.unary.Result\"\x00\x12#\n\x03Sub\x12\x0b.unary.Args\x1a\r.unary.Result\"\x00\x12$\n\x04Mult\x12\x0b.unary.Args\x1a\r.unary.Result\"\x00\x12#\n\x03\x44iv\x12\x0b.unary.Args\x1a\r.unary.Result\"\x00\x62\x06proto3')



_ARGS = DESCRIPTOR.message_types_by_name['Args']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
Args = _reflection.GeneratedProtocolMessageType('Args', (_message.Message,), {
  'DESCRIPTOR' : _ARGS,
  '__module__' : 'unary_pb2'
  # @@protoc_insertion_point(class_scope:unary.Args)
  })
_sym_db.RegisterMessage(Args)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'unary_pb2'
  # @@protoc_insertion_point(class_scope:unary.Result)
  })
_sym_db.RegisterMessage(Result)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'unary_pb2'
  # @@protoc_insertion_point(class_scope:unary.Message)
  })
_sym_db.RegisterMessage(Message)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'unary_pb2'
  # @@protoc_insertion_point(class_scope:unary.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

_UNARY = DESCRIPTOR.services_by_name['Unary']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ARGS._serialized_start=22
  _ARGS._serialized_end=56
  _RESULT._serialized_start=58
  _RESULT._serialized_end=99
  _MESSAGE._serialized_start=101
  _MESSAGE._serialized_end=127
  _MESSAGERESPONSE._serialized_start=129
  _MESSAGERESPONSE._serialized_end=181
  _UNARY._serialized_start=184
  _UNARY._serialized_end=403
# @@protoc_insertion_point(module_scope)
